#!/bin/bash

# Copyright (c) 2018-2019 Red Hat.
#
# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 3, or (at your
# option) any later version.
#
# It is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


# Test only creating dynamic notes.

rm -f hello.o

GCC=${GCC:-gcc}
READELF=${READELF:-readelf}
PLUGIN=${PLUGIN:-../gcc-plugin/.libs/annobin.so}

$GCC -fplugin=$PLUGIN -c -fplugin-arg-annobin-no-static-notes $srcdir/hello.c -fplugin-arg-annobin-dynamic-notes
