#!/bin/bash

# Copyright (c) 2017-2018 Red Hat.
#
# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 3, or (at your
# option) any later version.
#
# It is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

rm -f hello.o hello2.o hello3.o libhello.so function-sections-test.exe unused_code.o

set +v

GCC=gcc
READELF=readelf

PLUGIN=../plugin/.libs/annobin.so

$GCC -fplugin=$PLUGIN \
     -c \
     -fPIC \
     -Wall \
     -O1 \
     -ffunction-sections \
 $srcdir/hello.c 

$GCC -fplugin=$PLUGIN \
     -O3 \
     -c \
     -fPIC \
     -ffunction-sections \
 $srcdir/hello2.c 

$GCC -fplugin=$PLUGIN \
     -O2 \
     -c \
     -fpic \
     --save-temps \
     -ffunction-sections \
 $srcdir/unused_code.c \
     -o unused_code.o
if [ $? != 0 ];
then
    echo "$GCC does not support gexplicit stack protection.  Skipping test."
    exit 0
fi


$GCC -fplugin=$PLUGIN \
     -L . \
     -pie \
     -Wl,-z,now,-z,relro \
     -Wl,--gc-sections -Wl,--print-gc-sections \
     -Wl,-Map,fred.map \
 hello.o hello2.o unused_code.o -o function-sections-test.exe

# FIXME - we should check that the notes were parsed correctly...
$READELF --notes --wide function-sections-test.exe > /dev/null
