
jcc-scan: jcc-scan.o annocheck.o
	$(CC) -o $@ $^ -lelf -ldw -lrpm -lrpmio -liberty -lbfd -lopcodes

CFLAGS = -O2 -ansi -g -Wall -Werror

annocheck.o: annocheck.c annocheck.h
jcc-scan.o: jcc-scan.c annocheck.h

clean:
	rm -f *.o jcc-scan
